### ISSUE TITLE
Code theft?!

### ISSUE THREAD

**Issue by sdrygalski** [ashishbhandari/WatermarkCreator#1]
@ashishbhandari your BitmapDecoderTask https://github.com/ashishbhandari/WatermarkCreator/blob/master/library/src/main/java/com/watermarkcreator/library/BitmapDecoderTask.java 

is total rip off from this library: https://github.com/sharish/BitmapMerger/blob/master/app/src/main/java/com/cooltechworks/bitmapmerger/tasks/BitmapDecoderTask.java

How can you explain it? Why did you change original author in JavaDoc?

**Comment by ashishbhandari** [comment]
Might be i took it for my use .. i have updated the reference!
